# Generated by Django 5.2.16 on 2026-07-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("suppliers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="vat_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="supplier",
            name="vat_registered",
            field=models.BooleanField(default=False),
        ),
    ]
