# Generated by Django 5.2.16 on 2026-07-17 17:07

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("suppliers", "0003_supplier_shipping_policy"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="fulfilment_mode",
            field=models.CharField(
                choices=[
                    ("SUPPLIER_SHIP", "Supplier ships"),
                    ("PLATFORM_DELIVERY", "Platform-brokered delivery"),
                ],
                default="SUPPLIER_SHIP",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="platform_delivery_fee",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=8),
        ),
    ]
