# Generated by Django 5.2.16 on 2026-07-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0007_discount_codes"),
    ]

    operations = [
        migrations.AddField(
            model_name="suborder",
            name="fulfilment_mode",
            field=models.CharField(
                choices=[
                    ("SUPPLIER_SHIP", "Supplier ships"),
                    ("PLATFORM_DELIVERY", "Platform-brokered delivery"),
                ],
                default="SUPPLIER_SHIP",
                max_length=20,
            ),
        ),
    ]
