# Generated by Django 5.2.16 on 2026-07-17 20:14

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0008_platform_delivery"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReturnItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_items",
                        to="orders.orderitem",
                    ),
                ),
                (
                    "order_return",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.orderreturn",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
