# Generated by Django 5.2.16 on 2026-07-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0009_return_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="return_policy",
            field=models.CharField(
                choices=[
                    ("RETURNABLE", "Returnable (14-day change of mind)"),
                    ("DEFECTIVE_ONLY", "Defective only (via dispute)"),
                ],
                default="RETURNABLE",
                max_length=16,
            ),
        ),
    ]
