# Generated by Django 5.2.16 on 2026-07-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0010_orderitem_return_policy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="return_policy",
            field=models.CharField(
                choices=[
                    ("RETURNABLE", "Returnable (14-day change of mind)"),
                    ("DEFECTIVE_ONLY", "Defective only (via dispute)"),
                    ("SEALED", "Sealed for hygiene (returnable only if unopened)"),
                ],
                default="RETURNABLE",
                max_length=16,
            ),
        ),
    ]
