# Generated by Django 5.2.16 on 2026-07-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0004_payout_processing_started_at_payment_refund_request"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payout",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PROCESSING", "Processing"),
                    ("PAID", "Paid"),
                    ("FAILED", "Failed"),
                    ("REVERSED", "Reversed"),
                ],
                default="PENDING",
                max_length=12,
            ),
        ),
    ]
