# Generated by Django 5.2.15 on 2026-07-05 16:14

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orders", "0004_remove_orderdispute"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dispute",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "dispute_type",
                    models.CharField(
                        choices=[
                            ("NOT_RECEIVED", "Item not received"),
                            ("DAMAGED", "Item damaged or spoiled"),
                            ("WRONG_ITEM", "Wrong item received"),
                            ("PARTIAL_DELIVERY", "Partial delivery"),
                            ("FALSE_CLAIM", "False claim"),
                            ("DELIVERY_REFUSED", "Delivery refused by buyer"),
                            ("FRAUDULENT_CANCELLATION", "Fraudulent cancellation"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "resolution_requested",
                    models.CharField(
                        choices=[
                            ("FULL_REFUND", "Full refund"),
                            ("PARTIAL_REFUND", "Partial refund"),
                            ("REPLACEMENT", "Replacement"),
                            ("NO_ACTION", "No action"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("RESPONDENT_REPLIED", "Respondent replied"),
                            ("ESCALATED", "Escalated to admin"),
                            ("RESOLVED", "Resolved"),
                            ("CLOSED", "Closed"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FULL_REFUND", "Full refund"),
                            ("PARTIAL_REFUND", "Partial refund"),
                            ("REPLACEMENT", "Replacement"),
                            ("REJECTED", "Rejected (in favour of respondent)"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "outcome_amount_pence",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("outcome_notes", models.TextField(blank=True)),
                ("response_deadline", models.DateTimeField()),
                ("payout_held", models.BooleanField(default=True)),
                ("opened_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "opened_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="disputes_opened",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "respondent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="disputes_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sub_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="disputes",
                        to="orders.suborder",
                    ),
                ),
            ],
            options={
                "ordering": ["-opened_at"],
            },
        ),
        migrations.CreateModel(
            name="DisputeEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("OPENED", "Opened"),
                            ("RESPONDED", "Responded"),
                            ("ESCALATED", "Escalated"),
                            ("RESOLVED", "Resolved"),
                            ("CLOSED", "Closed"),
                            ("ADMIN_NOTE", "Admin note"),
                        ],
                        max_length=20,
                    ),
                ),
                ("body", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dispute_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dispute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="disputes.dispute",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="DisputeRefund",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("stripe_refund_id", models.CharField(max_length=100, unique=True)),
                ("amount_pence", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SUCCEEDED", "Succeeded"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dispute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refunds",
                        to="disputes.dispute",
                    ),
                ),
                (
                    "sub_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dispute_refunds",
                        to="orders.suborder",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
