# Generated by Django 5.2.15 on 2026-06-30 07:13

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalogue", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StockLevel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantity_available", models.PositiveIntegerField(default=0)),
                ("quantity_reserved", models.PositiveIntegerField(default=0)),
                ("low_stock_threshold", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "variant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock",
                        to="catalogue.productvariant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockLot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("lot_number", models.CharField(blank=True, max_length=100)),
                ("quantity_received", models.PositiveIntegerField()),
                ("quantity_remaining", models.PositiveIntegerField()),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lots",
                        to="catalogue.productvariant",
                    ),
                ),
            ],
            options={
                "ordering": ["expires_at", "received_at"],
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("INBOUND", "Inbound Receipt"),
                            ("OUTBOUND", "Outbound Dispatch"),
                            ("ADJUSTMENT", "Manual Adjustment"),
                            ("RETURN", "Customer Return"),
                            ("RESERVED", "Order Reserved"),
                            ("UNRESERVED", "Reservation Released"),
                        ],
                        max_length=12,
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("quantity_after", models.PositiveIntegerField()),
                ("reference", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_movements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to="catalogue.productvariant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
