# Generated by Django 5.2.16 on 2026-07-18 09:50

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orders", "0009_return_items"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourierDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("provider", models.CharField(max_length=40)),
                ("provider_quote_id", models.CharField(max_length=100)),
                ("provider_delivery_id", models.CharField(blank=True, max_length=100)),
                ("fee_charged", models.DecimalField(decimal_places=2, max_digits=8)),
                ("courier_cost", models.DecimalField(decimal_places=2, max_digits=8)),
                ("currency", models.CharField(default="GBP", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUOTED", "Quoted"),
                            ("BOOKED", "Booked"),
                            ("EN_ROUTE", "En route"),
                            ("DELIVERED", "Delivered"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="QUOTED",
                        max_length=12,
                    ),
                ),
                ("tracking_url", models.URLField(blank=True)),
                ("quote_expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sub_order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courier_delivery",
                        to="orders.suborder",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
