# Generated by Django 5.2.15 on 2026-07-05 16:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0002_add_banner_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="dispute_window_days",
            field=models.PositiveSmallIntegerField(
                default=3,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(7),
                ],
            ),
        ),
    ]
