# Generated by Django 5.2.15 on 2026-07-08 12:02

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0003_add_dispute_window_days"),
    ]

    operations = [
        migrations.CreateModel(
            name="VariantImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("url", models.URLField()),
                ("alt_text", models.CharField(blank=True, max_length=200)),
                ("position", models.PositiveIntegerField(default=0)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalogue.productvariant",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
    ]
