# Generated by Django 5.2.16 on 2026-07-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0004_variantimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="vat_rate",
            field=models.CharField(
                choices=[
                    ("STANDARD", "Standard (20%)"),
                    ("REDUCED", "Reduced (5%)"),
                    ("ZERO", "Zero (0%)"),
                ],
                default="STANDARD",
                max_length=10,
            ),
        ),
    ]
