# Generated by Django 5.2.16 on 2026-07-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0006_category_return_policy_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="return_policy",
            field=models.CharField(
                choices=[
                    ("RETURNABLE", "Returnable (14-day change of mind)"),
                    ("DEFECTIVE_ONLY", "Defective only (via dispute)"),
                    ("SEALED", "Sealed for hygiene (returnable only if unopened)"),
                ],
                default="DEFECTIVE_ONLY",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="return_policy_override",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RETURNABLE", "Returnable (14-day change of mind)"),
                    ("DEFECTIVE_ONLY", "Defective only (via dispute)"),
                    ("SEALED", "Sealed for hygiene (returnable only if unopened)"),
                ],
                default="",
                max_length=16,
            ),
        ),
    ]
