# Generated by Django 5.2.15 on 2026-07-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_dataexportrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="erased_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
